# active spring boot profile
spring:
   profiles:
      active: dev   

---

# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # message resource(Internationalization)
   messages:
      always-use-message-format: true
      basename: messages/messages_ko
      encoding: utf-8

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB 


---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

---

# server
server:
   port: 9099
   servlet:
     context-path:
     encoding:
        charset: utf-8
        enabled: true
        force: false
        force-request: false
        force-response: false

---
