# active spring boot profile
spring:
   profiles:
      active: dev   

---

# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # message resource(Internationalization)
   messages:
      always-use-message-format: true
      basename: messages/messages_ko
      encoding: utf-8

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB 


---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
         # datasource
   datasource:
      username: chat
      password: chat
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.219.104:3307/chat?characterEncoding=utf8
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
   jpa:
      # Spring Data JPA는 기본적으로 Hibernate라는 JPA 구현체를 사용한다. 
      # Hibernate는 내부적으로 지정되는 DB에 맞게 SQL 문을 생성하는 Dialect가 존재한다.
      # Dialect는 Hibernate가 다양한 데이터베이스를 처리하기 위해 각 데이터베이스에 맞는 (각기 다른) SQL 문법을 처리하기 위해 존재한다.
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
         # create-drop : SessionFactory가 시작될 때 Drop, Create, Alter를 하고 종료될때 Drop
         ddl-auto: create-drop
      properties:
         hibernate:
         # 콘솔창에서 실행되는 sql들을 보기좋게 보여주는 설정
            format_sql: true
            show_sql: true
---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

---

# server
server:
   port: 9099
   servlet:
     context-path: 
     encoding:
        charset: utf-8
        enabled: true
        force: false
        force-request: false
        force-response: false

---
